sudo: required

language: java

services:
  - docker

install:
  - chmod +x docker/certificates/create_certificates.sh && docker/certificates/create_certificates.sh
  - docker-compose up --detach --build

before_script:
  - mvn clean verify jacoco:report coveralls:report

script:
  - |
    count=1
    limit=120
    until docker ps --filter "name=$DOCKER_IMAGE" --filter "health=healthy" --format "{{.Names}}" | grep "$DOCKER_IMAGE"
    do
      echo "Testing container health $count of $limit"
      if [ $count -eq $limit ]; then
        echo "Docker container $DOCKER_IMAGE"
        exit 1
      fi
      sleep 1
      count=$((count + 1))
    done
    echo "Docker container $DOCKER_IMAGE is up and healthy"
  - cd docker-bench-security
  - sudo sh docker-bench-security.sh -c container_images
  - docker run -d --name db arminc/clair-db
  - docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6
  - clair-scanner -c "http://127.0.0.1:6060" --ip "$(ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')" $DOCKER_IMAGE:$service || true

